/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 iphone.gltf
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-iphone-14-pro-2023-928a8bf555224472b475b201561b2c2a
Title: (FREE) iPhone 14 Pro 2023
*/

import { useGLTF } from "@react-three/drei";

export default function Iphone(props: any) {
  const { nodes, materials }: any = useGLTF("/iphone.gltf");
  return (
    <group {...props} dispose={null} scale={30}>
      <group position={[0.01, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.frame} />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.FUNDO_SIN_CARD_21}
        />
        <mesh geometry={nodes.Object_6.geometry} material={materials.screen} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.back} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.island} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Labber} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.GLASS} />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.Lenscover}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.material_9}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group position={[-0.05, 0, -0.01]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.frame} />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.FUNDO_SIN_CARD_21}
        />
        <mesh geometry={nodes.Object_18.geometry} material={materials.screen} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.back} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.island} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Labber} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.GLASS} />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.Lenscover}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.material_9}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials["Material.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/iphone.gltf");
